name: Deploy to Google Cloud

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment.

    steps:
    - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.kendallryanlewis-1537384011284 }}
        service_account_key: ${{ secrets.-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCx6LPzmf5y1qJN\nPOQROMDMiZZHmozoW++fVsxPJaiJyuSofCmZi++krk2wKsSXBs5XVXupz261eAgu\nKfLXbMT03UqllfrxIkxTE75IvRPxHpGgf71iAovbMF8fbGahS28gQ/teWjy/mIYj\nHfH9Eo3FDHzvbdMEOE3U7o4pb4GNUP4wVEGpWHWfX2tBMTfGoKpDT8/VHlbsig7f\nVDTBRGJ5/G/2g/ArSFwSCwUVDJEf5c5NbdQ0/8NXUl9ggMSD0LtY0M3aiccUhoFg\n7QxP+s/xJS6PJXtGkVQ68Xjkijk7ocIZhEMMmF8o3Wajdr0crcuDVXZ1Ly9om86P\ndWympZOLAgMBAAECggEADQ9Fd8Teok8c0+mmiO3EbV9ONPcPOparxOO/agdG03Kd\njWar5msYzjBuCy1giADxEFp555xkBpXcl92Zch84aAx/Mx+K2mec+F490iNwaCXz\nz7crekXbPrL9e0DfBHO/9mY3I2p2r3ktTjz1ALxQxDMR+sDHmYreim/GkhvELqYw\nw4I6j6zB+8zuPd67zJtqP4yDSSGovFM6LYjBa8KItSH8astfxTigbNjqSGXBw5zc\nsguHc+8BY3D7ZR77zYN9lE7BavgoqmPMMbZbNC1RVOjjYPtivFTwk6+J9SffuA/4\nByX1ne0NREEdI1QFoD4LCBB3AXco+9CV5pGy6d2y7QKBgQDqA3xbObo31OIxLOeO\n0EiN6E8UzjOriUXI/9gjVAiYSmeDYDeuj88xPcUzE7qlx9mxKG9ozgPJnykH4XTW\nGvYAf7SqD1eUypnt4jwqqSzCDWb8FzyL3r1M+VAjnslzdkRw7a6wHdRKtnxJ4lxK\nWwZkvLETGEzxqEaM7Z6xCgXJ9wKBgQDCn8jK8FLvq7yKHRrOPN3umBGic9shIbpK\ndkbZLfKbB7JtoctO7FznPauHzyxcIuX4XIKHxpoQT6zifhzrUsgr1uI9neYPEWDO\nn4VUtKgswklnxLNEVMlLAgQ45kMQHPzjz9IFaw3gWjxbSG8NBnnqiz9b7PDeYrou\ned7QNfO+DQKBgE2YWEzbiG7o7RPHQwTs9ZHwfQB2G1X+z6AFjcKxI6Rzz30Vk4ET\neG1ogRIdsZ809G807DRBU6owV2egj6BLElU6A0r8iVryDzZ89Nxkek3iKcrfXZk3\ng2eZp8QX686YYbtcZLdLPNCFUBMjttyE8ErI8qJVRXZACRzD0gH8Q80jAoGBAKdP\nGxsye+mjdiI5IPkYpCTfP5GrDT6vMumeQgujj0Ks3DuY8iD32mnDvzix5c2TBqV6\nSZAVMA5DoDjY911pPcFKKhWULtjXNKSLx9/oqgZIQzhchUuBo8XChwSvFgm9Eb15\nw29692PdzrMeUrEc1yPE7wPEbdCPiMQ5ak0NhGrlAoGANVkdxT08Sr5Cam1bgXCP\nQPKTwVXXG32upJ5pL90aXULmCwZewK++mfAG/TeBnOe38uDawWiRq1iXOcshDlI8\nm+FF8GSrRwBQORwqRga75hxo2NK5RwRp7npQgS7Niyd/ZJj9TroDy5LgsrKnJxBR\ntMHbXyTN5OO6N5TEunW3c5c=\n-----END PRIVATE KEY-----\n}}
        export_default_credentials: true

    - name: Deploy to Google App Engine
      run: |
        gcloud app deploy
